[project]
name = "hexgraphics"
version = "0.3.1"
authors = [
  { name="noobiezt0" },
]
description = "aka 0xg"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Source = "https://github.com/noobiezt0/0xg"

[build-system]
requires = ["pillow", "setuptools"]
build-backend = "setuptools.build_meta"
