[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "opentrustprotocol"
version = "1.0.6"
authors = [
  { name="OpenTrust Protocol Team", email="contact@opentrustprotocol.com" },
]
description = "The official SDK for the OpenTrust Protocol, the open standard for auditable trust."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
keywords = ["neutrosophy", "neutrosophic", "uncertainty", "trust", "audit", "ai", "otp"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Security",
]

[project.urls]
Homepage = "https://opentrustprotocol.com"
Documentation = "https://opentrustprotocol.com"
Repository = "https://github.com/draxork/opentrustprotocol"

