[project]
name = "yta-video-pyav"
version = "0.3.14"
description = "Youtube Autonomous Video PyAv Module"
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    "yta_validation (>=0.0.1,<1.0.0)",
    "yta_video_frame_time (>=0.0.1,<1.0.0)",
    "yta_constants (>=0.0.1,<1.0.0)",
    "av (>=0.0.1,<99.0.0)",
    "numpy (>=0.0.1,<9.0.0)",
    "quicktions (>=0.0.1,<9.0.0)",
]

[tool.poetry]
packages = [{include = "yta_video_pyav", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
yta_testing = ">=0.0.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
