[project]
name = "tabsmith"
version = "0.1.1"
license = { file = "LICENSE" }
description = "Tabsmith: Fitting multi-target tabular ML classifiers with overlapping inputs and targets."
readme = "README.md"
authors = [
    { name = "Chinmay Kakatkar", email = "kcpub21@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=1.21",
    "pandas>=1.3",
    "scikit-learn>=1.0",
    "tabulate>=0.9.0",
]

[project.urls]
Homepage = "https://github.com/ckstash/tabsmith"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
