[project]
name = "justrunalready"
version = "0.1.12"
description = "Win/Linux/Mac bundler helper."
readme = "README.md"
authors = [
    { name = "Tyler Kennedy", email = "tk@tkte.ch" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["justrunalready"]

[tool.hatch.build.targets.sdist]
include = [
  "justrunalready",
  "README.md",
  "pyproject.toml",
]

[project.scripts]
jra = "justrunalready.cli:main"

[project.optional-dependencies]
inspect = [
  "pyelftools; platform_system=='Linux'",
  "macholib; platform_system=='Darwin'",
  "pefile; platform_system=='Windows'",
]
dev = [
  "pytest",
]

[project.entry-points."justrunalready.plugins"]
qt = "justrunalready.plugins.qt:QtPlugin"

[project.entry-points."justrunalready.platforms"]
linux = "justrunalready.platforms.linux:LinuxPlatform"
windows = "justrunalready.platforms.windows:WindowsPlatform"
macos = "justrunalready.platforms.macos:MacOSPlatform"

[project.entry-points."justrunalready.wrappers"]
appimage = "justrunalready.wrappers.appimage:AppImageWrapper"
dmg = "justrunalready.wrappers.dmg:DmgWrapper"
zip = "justrunalready.wrappers.zip:ZipWrapper"

[project.entry-points."justrunalready.inspectors"]
linux = "justrunalready.inspectors.linux:LinuxInspector"
windows = "justrunalready.inspectors.windows:WindowsInspector"
macos = "justrunalready.inspectors.macos:MacOSInspector"
