[project]
name = "agentspro"
version = "0.1.1"
description = "The AI Agent Decorator SDK for Agentspro platform integration"
readme = "README.md"
authors = [
    { name = "Hehua Fan", email = "forhheart5532@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "PyYAML>=6.0",
    "pydantic>=2.11.7",
    "requests>=2.32.4"
]

[project.scripts]
agentspro-python-sdk = "agentspro:main"

[tool.hatch.build.targets.wheel]
packages = ["src/agentspro"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"