[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nixscribe"
version = "0.1.1"
description = "A CLI Text Editor that supports Syntax Highlighting for .py, .html, .css and .js files."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [{name = "mhasanali2010"}]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

dependencies = [
    "rich>=13.5.2",
    "prompt_toolkit>=3.0.52",
    "pygments>=2.17.1",
]

[project.scripts]
nixscribe = "nixscribe.cli:main"
