[project]
name = "cppref"
version = "0.1.1"
description = "Refer to the cppreference with this cli!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "lxml>=6.0.0",
    "playwright>=1.55.0",
    "toml>=0.10.2",
    "tqdm>=4.67.1",
    "types-lxml>=2025.3.30",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"
module-name = "cppref"
