[project]
name = "phu"
version = "0.4.4"
description = "Phage bioinformatics utilities (seqclust runner and friends)."
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Camilo GarcÃ­a-Botero", email = "ca.garcia2@uniandes.edu.co" }
]
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.2",
    "pyhmmer>=0.11.1",
    "pyrodigal>=3.6.3.post1",
    "pyrodigal-gv>=0.3.2",
    "typer>=0.17.3",
]

[project.scripts]
phu = "phu.cli:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest>=8.4.1"
]
lint = [
    "ruff>=0.12.11",
]
