[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "thesis-py"
version = "1.0.2"
description = "Python SDK for Thesis.io APIs."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "GNU General Public License v3.0" }
authors = [{ name = "Oraichain Labs", email = "duc@orai.io" }]
dependencies = [
    "requests>=2.32.3",
    "typing-extensions>=4.12.2",
    "openai>=1.48",
    "pydantic>=2.10.6",
    "httpx>=0.28.1",
    "httpcore>=1.0.9",
    "python-dotenv>=1.0.1",
    "litellm",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "pytest-cov>=6.2.1",
    "pytest-mock>=3.14.1",
    "setuptools>=80.9.0",
]

[tool.setuptools.packages.find]
include = ["thesis_py*"]
