[project]
name = "shudaodao"
version = "0.1.15"
description = "SmartShudao"
readme = "README.md"
authors = [
    { name = "SmartShudao", email = "lf_shao@163.com" },
]
# 或者使用 SPDX 标识符
license = "MIT"
# 同时可以指定许可证文件
license-files = ["LICENSE"]

requires-python = ">=3.10"

dependencies = [
    "aiosqlite>=0.21.0",
    "asyncpg>=0.30.0",
    "casbin>=1.43.0",
    "casbin-async-sqlalchemy-adapter>=1.10.0",
    "cython>=3.1.2",
    "fastapi>=0.115.12",
    "greenlet>=3.2.4",
    "numpy>=2.2.6",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.10",
    "pydantic[email]>=2.11.7",
    "pytest>=8.4.1",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "redis>=6.4.0",
    "setuptools>=80.9.0",
    "sqlalchemy>=2.0.43",
    "sqlmodel>=0.0.24",
    "starlette>=0.46.2",
    "uvicorn>=0.34.3",
]

[build-system]
requires = ["setuptools", "wheel", "Cython>=3.1.2"]
build-backend = "setuptools.build_meta"

#[[tool.uv.index]]
#url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
#default = true