[project]
name = "matrixmethod"
version = "0.1.2"
requires-python = ">=3.12"
dependencies = [
    "numba>=0.62.0",
    "numpy>=2.3.3"
]
authors = [
    {name = "Mika Pflueger"},
    {name = "Kas Andrle",email = "kandrle@lbl.gov"}
    ]
description = "Calculating Refelctivity"
readme = "README.md"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.ruff]
exclude = [
  ".github",
  ".git",
  ".vscode",
  "docs",
  "src",
]
fix = true
line-length = 88