[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SarthakFraction"
version = "0.1.1"
description = "A human-friendly Python package for fraction operations"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name="Sarthak Bora", email="youremail@example.com" }
]
requires-python = ">=3.7"
dependencies = []

[project.urls]
Homepage = "https://github.com/Dev-SarthakBora/SarthakFraction"

