#:schema https://json.schemastore.org/pyproject.json
# ref: <https://packaging.python.org/en/latest/specifications/pyproject-toml/>

[project]
name = "liblaf-tangerine"
description = "ðŸŠ Squeeze dynamic content into your files with Tangerine's template magic."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
  { name = "liblaf", email = "30631553+liblaf@users.noreply.github.com" },
]
keywords = []
classifiers = [
  # ref: <https://pypi.org/classifiers/>
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Typing :: Typed",
]
dependencies = [
  "attrs>=25,<26",
  "cappa>=0.30,<0.31",
  "cytoolz>=1,<2",
  "emoji>=2.14.1",
  "githubkit>=0.13,<0.14",
  "gitpython>=3,<4",
  "jinja2>=3,<4",
  "lazy-loader>=0.4,<0.5",
  "liblaf-grapes>=4,<5",
  "loguru>=0.7,<0.8",
  "platformdirs>=4,<5",
]
dynamic = ["version"]

[project.urls]
# ref: <https://packaging.python.org/en/latest/specifications/well-known-project-urls/#well-known-labels>
"Changelog" = "https://github.com/liblaf/tangerine/blob/main/CHANGELOG.md"
"Documentation" = "https://liblaf.github.io/tangerine/"
"Funding" = "https://github.com/liblaf/tangerine?sponsor=1"
"Homepage" = "https://github.com/liblaf/tangerine"
"Issue Tracker" = "https://github.com/liblaf/tangerine/issues"
"Release Notes" = "https://github.com/liblaf/tangerine/releases"
"Source Code" = "https://github.com/liblaf/tangerine"

[project.scripts]
tangerine = "liblaf.tangerine:main"

[dependency-groups]
build = ["check-wheel-contents>=0.6,<0.7", "hatch>=1,<2", "twine>=6,<7"]
dev = ["icecream>=2,<3"]
docs = ["liblaf-mkdocs-preset>=0.2,<0.3", "mkdocs>=1,<2"]
test = ["liblaf-pytest-preset>=0.1,<0.2", "pytest>=8,<9"]

[build-system]
requires = ["hatch-vcs", "hatchling"]
build-backend = "hatchling.build"

[tool.check-wheel-contents]
ignore = ["W002"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.hatch.build.hooks.vcs]
version-file = "src/liblaf/tangerine/_version.py"

[tool.hatch.build.targets.sdist]
only-include = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/liblaf"]

[tool.hatch.version]
source = "vcs"

[tool.pyright]
extends = ".config/linters/pyrightconfig.json"

[tool.pytest.ini_options]
addopts = [
  "--doctest-modules",
  "--hypothesis-show-statistics",
  "--import-mode=importlib",
  "--showlocals",
  "--strict-config",
  "--strict-markers",
]
testpaths = ["benches", "src", "tests"]

[tool.ruff]
extend = ".config/linters/.ruff.toml"

[tool.uv]
default-groups = "all"
