[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "graphs_csirhall"
version = "0.0.3"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "A Python package for graph algorithms including Dijkstra's shortest path"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/csirhall/dijkstra-sp"
"Bug Tracker" = "https://github.com/csirhall/dijkstra-sp/issues"