[build-system]
requires = [
    "setuptools>=61.0",
    "flask"
]
build-backend = "setuptools.build_meta"

[project]
name = "PyWebApp3"                   # The name users install with pip
version = "0.1.2"                  # Change this when you upgrade
description = "PyWeb is a Python-based web framework that allows you to build responsive, modern web applications using only Python code. No HTML, CSS, or JavaScript knowledge required!"
readme = "README.md"
authors = [{ name="Alex Austin", email="benmap40@gmail.com" }]
license = { text = "MIT" }
requires-python = ">=3.7"