[project]
name = "pyfigo"
version = "0.1.4"
description = "Get OBJECT keyword from a fits file"
authors = [{name = "JoaÌƒo Faria", email = "joao.faria@unige.ch"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools]
py-modules = ["figo"]
ext-modules = [
  {name = "cfigo", sources = ["figo.c"]}
]

[project.scripts]
figo = "figo:_main"