[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py-eawrc-sdk"
version = "0.0.3"
requires-python = ">=3.9"
authors = [
  { name="Josh Delima", email="jDelima14@gmail.com" }
]
description = "Python library to help aid access to EA WRC telemetry"
keywords = ["EA WRC", "Telemetry", "SDK"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/ChequeredFox/py-eawrc-sdk/"
Issues = "https://github.com/ChequeredFox/py-eawrc-sdk/issues"