# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arcscript"
version = "0.1.1-alpha"
authors = [
  { name="Aditya Tiwari", email="contact.aditya108@gmail.com" },
]
description = "A simple language that transpiles to JavaScript for easier web development."
readme = "README.md"
requires-python = ">=3.7"
license = { text="GPL-3.0-or-later" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Compilers",
]
dependencies = [
    "lark",
]

[project.urls]
"Homepage" = "https://github.com/aditya-tiwari108/ArcScript"
"Bug Tracker" = "https://github.com/aditya-tiwari108/ArcScript/issues"

[project.scripts]
arcscript = "arcscript.cli:main"
