[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "django_utility_suite"
version = "v0.1.11" # version managed with gitlab tags
description = "A Django utility suite with additional features"
authors = ["toni <tonicapagarcia@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = ">=3.0"
djangorestframework = ">=3.11"
xxhash = "^3.5.0"
