[project]
name = "blindscrambler"
version = "0.1.5"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "blindscramblergh", email = "blindscrambler@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "torch>=2.8.0",
    "twine>=6.1.0",
]

[tool.maturin]
module-name = "blindscrambler._core"
python-packages = ["blindscrambler"]
python-source = "src"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
