[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "blackjackFire"
version = "1.2.1"
description = "A terminal-based Blackjack game"
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
authors = [
  { name = "FireShade3DS", email = "ben042010@icloud.com" }
]


dependencies = [
  "termcolor",
  "colorama"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Environment :: Console",
  "Topic :: Games/Entertainment :: Board Games"
]

[project.scripts]
blackjack = "bjpack.main:main"

[tool.setuptools]
packages = ["bjpack"]