[tool.poetry]
name = "busy"
description = "Escape from overwhelm and stay focused all day"
authors = ["Steampunk Wizard <busy@steamwiz.io>"]
license = "MIT"
readme = "PACKAGE.md"
version = "7.14.3"
homepage = 'https://steamwiz.io'
repository = 'https://gitlab.com/steamwiz/busy'

[tool.poetry.dependencies]
# packaging = "^25.0"   # Why is this necessary?
python = "~3.11"
wizlib = "3.3.7"
platformdirs = "^3.10.0"
reportlab = "^4.0.4"
mcp = {extras = ["cli"], version = "^1.2.0"}
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
pycodestyle = "^2.11.0"
autopep8 = "^2.0.4"
coverage = "^7.3.0"

[tool.poetry.scripts]
busy = "busy:BusyApp.main"
