[project]
name = "huizhi-coupon-lengyue1084"
version = "0.1.1"
description = "这是一个优惠券转化工具"
authors = [
  { name = "lengyue1084", email = "95695864@qq.com" },
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = [
    "mcp", # 基础包
]

[project.scripts]
calculate-tool-lengyue1084 = "huizhi_coupon_lengyue1084.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/huizhi_coupon_lengyue1084"]

[tool.hatch.build.targets.sdist]
packages = ["src/huizhi_coupon_lengyue1084"]
