# tools/cli/pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ming-drlms"
version = "0.2.0"
description = "CLI wrapper for DRLMS server/agent with pretty UX"
readme = "README.md"
authors = [{ name = "lgnorant-lu", email = "zhouzihan825@gmail.com" }]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
requires-python = ">=3.8"
dependencies = [
    "typer[all]",
    "pyyaml",
    "rich",
    "psutil",
]

[project.urls]
"Source" = "https://github.com/lgnorant-lu/ming-drlms"

[project.scripts]
ming-drlms = "ming_drlms.main:app"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true
