[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "django-code-audit"
version = "0.2.6"  # <-- Increment version
description = "A Django app for auditing Python code using pylint"
readme = "README.md"

requires-python = ">=3.8"
authors = [
  { name = "Ravi K", email = "kravi2439@gmail.com" },
]
license = { text = "MIT" }
keywords = [
    "django",
    "pylint",
    "code audit",
    "code quality",
    "django admin",
    "static analysis",
    "linting",
    "audit",
    "python quality"
]
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 4.0",
    "Framework :: Django :: 5.0",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing",
    "Programming Language :: Python :: 3",
]

dependencies = [
    "Django>=4.0",
    "pylint>=3.0",
    "pylint-json2html",
    "pylint-report"
]

[project.urls]
Homepage = "https://github.com/ravikempanayaka/Code-Audit#"
