[project]
name = "mtl_agent"
version = "0.3.3"
dependencies = ["ass_tag_parser", "ass", "playwright", "ffmpeg-python", "pillow", "requests", "better_ffmpeg_progress"]
authors = [{name="Matey Krastev", email="matey.krastev@outlook.com"}]
license={text="MIT"}
readme = "README.md"
requires-python = ">=3.7"
description = "MTL agent for media processing"

[project.scripts]
mtl_agent = "mtl_agent.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
