[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stk_widgets"
version = "0.1.1"
description = "Custom widgets for tkinter"
authors = [{name = "Oladapo Akintola"}]
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
keywords = ["tkinter", "widgets", "GUI"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]
dependencies = [
    "customtkinter",
    "Pillow",
]

[project.urls]
Homepage = "https://github.com/OladapoAkintola/stk-widgets"

[tool.setuptools.packages.find]
where = ["."]
include = ["stk_widgets"]
