[project]
name = "create-browser-app"
version = "0.1.3"
description = "Start your Stagehand project with a single command"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "stagehand",
    "click>=8.0",
    "rich>=13.0",
    "inquirer>=3.0"
]

[project.scripts]
create-browser-app = "main:main"
