[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wayne-trade"
version = "0.1.6"
description = "Formula to model matrix converter"
requires-python = ">=3.13"
authors = [{ name = "Alex Hallam", email = "alexhallam628@gmail.com" }]
dependencies = ["polars>=1.8.2", "numpy>=1.21.0", "fiasto-py>=0.1.4"]
license = { text = "MIT" }
readme = "README.md"

[project.optional-dependencies]
dev = ["pytest>=7.0.0", "pytest-cov>=4.0.0"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
wayne = ["*.py"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Rust",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

keywords = ["formula", "parser", "statistics", "mixed-effects", "wilkinson"]
