[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xpath-kit"
version = "0.3.11"
description = "A toolkit for convenient and expressive XPath operations based on lxml."
authors = [{ name = "Kabxx", email = "2201174299@qq.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["lxml>=6.0.0"]
keywords = ["xpath", "lxml", "xml", "html", "parser"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.isort]
profile = "black"
src_paths = ["src/xpathkit", "tests"]

[project.optional-dependencies]
test = ["pytest"]
