[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "openaleph-client"
version = "1.1.1"
description = "Python client for the OpenAleph data API"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
  { name = "Data and Research Center - DARC", email = "hi@dataresearchcenter.org" },
]
urls = { "Repository" = "https://github.com/dataresearchcenter/opal-client" }
dependencies = [
  "banal>=1.0.1,<2.0.0",
  "pyyaml>=5.0.0,<7.0.0",
  "requests>=2.21.0,<3.0.0",
  "requests_toolbelt>=1.0.0,<2.0.0",
  "urllib3>=1.26.0,<2.0.0",
  "click>=7.0,<9.0",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
  "mypy",
  "wheel",
  "pytest",
  "pytest-mock>=1.10.0",
  "types-requests",
  "types-setuptools",
]

[project.scripts]
openaleph = "openaleph.cli:cli"

[tool.setuptools.packages.find]
include = ["openaleph", "openaleph.*"]
exclude = ["openaleph.tests", "openaleph.tests.*"]
