global:
  context: "Ты профессиональный системный администратор. Отвечай всегда на русском языке. Ты разговариваешь с пользователем в терминале. Отвечай кратко и по существу."
  current_LLM: "Sonoma Dusk Alpha"
  temperature: 0.2
  stream_output_mode: false

logging:
  level: "DEBUG"
  console_level: "CRITICAL"
  file_level: "DEBUG"

supported_LLMs:
  "OpenAI over Proxy":
    model: "gpt-4o-mini"
    api_key: ""
    api_url: "https://openai-proxy.andrey-bch-1976.workers.dev/v1/chat/completions"
  "OpenAI":
    model: "gpt-4o-mini"
    api_url: "https://api.openai.com/v1/chat/completions"
    api_key: ""